USE sample_data;

DROP TABLE IF EXISTS ReviewVotes;
DROP TABLE IF EXISTS Favorites;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Discount;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Restaurant;
DROP TABLE IF EXISTS Users;

DROP DATABASE IF EXISTS sample_data;
